from abc import ABC, abstractmethod
from enum import Enum
from typing import Optional
from pydantic import BaseModel
from src.models.domain import Stock

class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

class Signal(BaseModel):
    """Represents a trading signal generated by a strategy."""
    symbol: str
    signal_type: SignalType
    strength: float = 1.0 # 0.0 to 1.0 confidence
    reason: Optional[str] = None

class Strategy(ABC):
    """Abstract base class for trading strategies."""
    
    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def analyze(self, stock: Stock) -> Signal:
        """
        Analyzes the stock data and returns a trading signal.
        
        Args:
            stock: The stock object containing price history and indicators.
            
        Returns:
            A Signal object (BUY, SELL, or HOLD).
        """
        pass
